jobs:
  - name: Download Cleanup
    directories:
      downloads: ~/Downloads
      documents: ~/Documents/mildred-test
    tasks:
      - Move any documents or presentations from downloads to documents
